#!/usr/bin/python3

import os, sys
from getpass import getpass
import paramiko
from paramikoe import SSHClientInteraction

# initialize variables
port = 22
asa_address = 'REDACTED'
asa_username = input("username (enter for REDACTED): ")
asa_password = getpass()
asa_timeout = 15
asa_port = 22
asaprompt = ".*# "
ssh_known_hosts = "~/.ssh/known_hosts"
debug=False

# additional initialization
ssh_known_hosts = os.path.expanduser(ssh_known_hosts)
if not asa_username:
	asa_username = 'REDACTED'
enable_password = asa_password
if debug:
	paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)

# figure out what we're banning
try:
	ip = sys.argv[1]
except:
	ip = input("what IP would you like to ban? ")

# create child process
client=paramiko.SSHClient()
#child = pexpect.spawn('ssh -M -p %d %s@%s' %(port, username, hostname))
client.load_host_keys(ssh_known_hosts)
client.connect(asa_address, port=asa_port, username=asa_username, password=asa_password, timeout=asa_timeout, look_for_keys=False)
interact=SSHClientInteraction(client, timeout=asa_timeout, display=debug)

#log in and set some environment stuff
interact.expect(".*>.*")
interact.send("en")
interact.expect(".*Password:.*")
interact.send(enable_password)
interact.expect(asaprompt)
interact.send("configure terminal")
interact.expect(asaprompt)
interact.send("terminal pager 0")
interact.expect(asaprompt)
interact.send("terminal width 200")
interact.expect(asaprompt)

# ban
interact.send("object-group network blacklisted_IPs")
interact.expect(asaprompt)
interact.send("network-object host " + ip)
interact.expect(asaprompt)

# close connection
client.close()
